version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-apache
    restart: always
    ports:
      - "8080:80"  # Apache expose le port 80 sur le port 8080 du VPS
    volumes:
      - ./web:/var/www/web
    networks:
      - proxy-net

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"  # Nginx écoute sur le port 80 pour gérer DuckDNS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-apache
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
